CREATE DATABASE AcademyDB;

USE AcademyDB;



CREATE TABLE Teachers (
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Name NVARCHAR(MAX) NOT NULL CHECK (LEN(Name) > 0),
    Surname NVARCHAR(MAX) NOT NULL CHECK (LEN(Surname) > 0)
);


CREATE TABLE Assistants (
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    TeacherId INT NOT NULL FOREIGN KEY REFERENCES Teachers(Id)
);


CREATE TABLE Curators (
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    TeacherId INT NOT NULL FOREIGN KEY REFERENCES Teachers(Id)
);


CREATE TABLE Heads (
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    TeacherId INT NOT NULL FOREIGN KEY REFERENCES Teachers(Id)
);


CREATE TABLE Deans (
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    TeacherId INT NOT NULL FOREIGN KEY REFERENCES Teachers(Id)
);


CREATE TABLE Faculties (
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Building INT NOT NULL CHECK (Building BETWEEN 1 AND 5),
    Name NVARCHAR(100) NOT NULL UNIQUE CHECK (LEN(Name) > 0),
    DeanId INT NOT NULL FOREIGN KEY REFERENCES Deans(Id)
);


CREATE TABLE Departments (
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Building INT NOT NULL CHECK (Building BETWEEN 1 AND 5),
    Name NVARCHAR(100) NOT NULL UNIQUE CHECK (LEN(Name) > 0),
    FacultyId INT NOT NULL FOREIGN KEY REFERENCES Faculties(Id),
    HeadId INT NOT NULL FOREIGN KEY REFERENCES Heads(Id)
);


CREATE TABLE Groups (
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Name NVARCHAR(10) NOT NULL UNIQUE CHECK (LEN(Name) > 0),
    Year INT NOT NULL CHECK (Year BETWEEN 1 AND 5),
    DepartmentId INT NOT NULL FOREIGN KEY REFERENCES Departments(Id)
);


CREATE TABLE GroupsCurators (
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    CuratorId INT NOT NULL FOREIGN KEY REFERENCES Curators(Id),
    GroupId INT NOT NULL FOREIGN KEY REFERENCES Groups(Id)
);


CREATE TABLE Subjects (
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Name NVARCHAR(100) NOT NULL UNIQUE CHECK (LEN(Name) > 0)
);


CREATE TABLE LectureRooms (
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Building INT NOT NULL CHECK (Building BETWEEN 1 AND 5),
    Name NVARCHAR(10) NOT NULL UNIQUE CHECK (LEN(Name) > 0)
);


CREATE TABLE Lectures (
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    SubjectId INT NOT NULL FOREIGN KEY REFERENCES Subjects(Id),
    TeacherId INT NOT NULL FOREIGN KEY REFERENCES Teachers(Id)
);


CREATE TABLE GroupsLectures (
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    GroupId INT NOT NULL FOREIGN KEY REFERENCES Groups(Id),
    LectureId INT NOT NULL FOREIGN KEY REFERENCES Lectures(Id)
);


CREATE TABLE Schedules (
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Class INT NOT NULL CHECK (Class BETWEEN 1 AND 8),
    DayOfWeek INT NOT NULL CHECK (DayOfWeek BETWEEN 1 AND 7),
    Week INT NOT NULL CHECK (Week BETWEEN 1 AND 52),
    LectureId INT NOT NULL FOREIGN KEY REFERENCES Lectures(Id),
    LectureRoomId INT NOT NULL FOREIGN KEY REFERENCES LectureRooms(Id)
);
